### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by JorgeAnzola** [muehlt/home-assistant-findmy#1]
I'm getting the following issue when trying to execute the class

`~/home-assistant-findmy(main*) » sudo python3 findmy.py                                                                                                                                                                                                    JORGE.ANZOLAOROPEZA@macbook
Password:
Traceback (most recent call last):
  File "/Users/JORGE.ANZOLAOROPEZA/home-assistant-findmy/findmy.py", line 35, in <module>
    from halo import Halo
  File "/Users/JORGE.ANZOLAOROPEZA/Library/Python/3.9/lib/python/site-packages/halo/__init__.py", line 7, in <module>
    from .halo import Halo
  File "/Users/JORGE.ANZOLAOROPEZA/Library/Python/3.9/lib/python/site-packages/halo/halo.py", line 18, in <module>
    from halo._utils import (
  File "/Users/JORGE.ANZOLAOROPEZA/Library/Python/3.9/lib/python/site-packages/halo/_utils.py", line 6, in <module>
    import six
ModuleNotFoundError: No module named 'six'`

`~/home-assistant-findmy(main*) » pip3 install -r requirements.txt                                                                                                                                                                                          JORGE.ANZOLAOROPEZA@macbook
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: halo==0.0.31 in /Users/JORGE.ANZOLAOROPEZA/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 1)) (0.0.31)
Requirement already satisfied: paho_mqtt==1.6.1 in /Users/JORGE.ANZOLAOROPEZA/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 2)) (1.6.1)
Requirement already satisfied: python-dotenv==0.21.0 in /Users/JORGE.ANZOLAOROPEZA/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 3)) (0.21.0)
Requirement already satisfied: Unidecode==1.3.6 in /Users/JORGE.ANZOLAOROPEZA/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 4)) (1.3.6)
Requirement already satisfied: spinners>=0.0.24 in /Users/JORGE.ANZOLAOROPEZA/Library/Python/3.9/lib/python/site-packages (from halo==0.0.31->-r requirements.txt (line 1)) (0.0.24)
Requirement already satisfied: six>=1.12.0 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from halo==0.0.31->-r requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: colorama>=0.3.9 in /Users/JORGE.ANZOLAOROPEZA/Library/Python/3.9/lib/python/site-packages (from halo==0.0.31->-r requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: termcolor>=1.1.0 in /Users/JORGE.ANZOLAOROPEZA/Library/Python/3.9/lib/python/site-packages (from halo==0.0.31->-r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: log-symbols>=0.0.14 in /Users/JORGE.ANZOLAOROPEZA/Library/Python/3.9/lib/python/site-packages (from halo==0.0.31->-r requirements.txt (line 1)) (0.0.14)`

**Comment by muehlt** [comment]
`six` is one of `halo`'s dependencies (`log-symbols, termcolor, six, colorama, spinners`) used for compatibility to python2.

It looks like a conflict - please first try to update to the most recent version of `six` [1].

[1] [https://pypi.org/project/six/](https://pypi.org/project/six/)

**Comment by muehlt** [comment]
`six` is one of `halo`'s dependencies (`log-symbols, termcolor, six, colorama, spinners`) and used for compatibility to python2. Looks like some conflict in your setup - I'd first try to update to the most recent version of `six` (currently 1.16.0) [1]. If that doesn't change anything you should try to cleanly install the dependencies.

[1] [https://pypi.org/project/six/](https://pypi.org/project/six/)
