### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted: '/Users/jdyer/Library/Caches/com.apple.findmy.fmipcore/Items.data'

### ISSUE THREAD

**Issue by johntdyer** [muehlt/home-assistant-findmy#14]
**Describe the bug**

**To Reproduce**
1. run application

**Expected behavior**
App to start

**Screenshots**
```
╭─    ~/Projects/home-assistant-findmy/findmy    main ?2                                                                               1 ✘  ▼  10:56:31 AM  ─╮
╰─ findmy -l ../test.json                                                                                                                                          ─╯
Traceback (most recent call last):
  File "/opt/homebrew/bin/findmy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/findmy/__init__.py", line 320, in main
    scan_cache(privacy, force_sync)
  File "/opt/homebrew/lib/python3.11/site-packages/findmy/__init__.py", line 219, in scan_cache
    send_data_items(force_sync)
  File "/opt/homebrew/lib/python3.11/site-packages/findmy/__init__.py", line 107, in send_data_items
    for device in load_data(cache_file_location_items):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/findmy/__init__.py", line 78, in load_data
    with open(data_file, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: '/Users/jdyer/Library/Caches/com.apple.findmy.fmipcore/Items.data'
╭─    ~/Projects/home-assistant-findmy/findmy    main ?2                                                                               1 ✘  ▼  10:56:51 AM  ─╮
╰─ ls -la /Users/jdyer/Library/Caches/com.apple.findmy.fmipcore/Items.data                                                                                         ─╯
-rw-r--r--@ 1 jdyer  staff  18142 Sep 25 10:56 /Users/jdyer/Library/Caches/com.apple.findmy.fmipcore/Items.data
╭─    ~/Projects/home-assistant-findmy/findmy    main ?2                                                                                ✔ │ ▼  10:56:57 AM  ─╮
╰─
```

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser n/a

**Smartphone (please complete the following information):**
 - Device: iPhone 15
 - OS: 17

**Comment by johntdyer** [comment]
nevermind, iTerm didnt have full disk access
