### ISSUE TITLE
home-assistant-findmy 1.1.0 stopped working after macOS update to 14.4（23E214）

### ISSUE THREAD

**Issue by degucci** [muehlt/home-assistant-findmy#27]
**Describe the bug**
Thank you very much for maintain home-assistant-findmy
Home-assistant-findmy 1.1.0 does not start at all after I update macOS to 14.4 (23E214).

**To Reproduce**
/Users/*****/Library/Python/3.9/bin/findmy  -l  /Users/*****/FindMytoHA/known_locations.json  --ip 192.168.x.xxx --username YYYYY --password ZZZZZ

**Expected behavior**
Before OS update, It worked fine.

**Smartphone (please complete the following information):**
 - Device: MacMini M1
 - OS: macOS 14.4（23E214）

**Additional context**
Traceback (most recent call last):
  File "/Users/*****/Library/Python/3.9/bin/findmy", line 8, in <module>
    sys.exit(main())
  File "/Users/*****/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/*****/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/*****/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/*****/Library/Python/3.9/lib/python/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/*****/Library/Python/3.9/lib/python/site-packages/findmy/__init__.py", line 322, in main
    scan_cache(privacy, force_sync)
  File "/Users/*****/Library/Python/3.9/lib/python/site-packages/findmy/__init__.py", line 221, in scan_cache
    send_data_items(force_sync)
  File "/Users/*****/Library/Python/3.9/lib/python/site-packages/findmy/__init__.py", line 107, in send_data_items
    for device in load_data(cache_file_location_items):
  File "/Users/*****/Library/Python/3.9/lib/python/site-packages/findmy/__init__.py", line 79, in load_data
    data = json.load(f)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 8: invalid continuation byte

**Comment by degucci** [comment]
Seems files in the folder "com.apple.findmy.fmipcore" seems to be encrypted. So it does not work. I downgraded macOS to 14.3.

**Comment by muehlt** [comment]
Hi, thanks for the finding. I will look deeper into it soon and leave a note in the README for now.

**Comment by bvlaicu** [comment]
@muehlt Thank you very much for your work on this component. Did you get a chance to look into this issue? Any hopes for a fix?

**Comment by muehlt** [comment]
Hi @bvlaicu, unfortunately, I still couldn't have a deeper dive into it. I think I can fix it by June/July or even look into a better technique of capturing AirTag data (without a Mac running 24/7) since Apple changed how they handle them on iCloud itself. I'm also waiting for new hardware to test it on since I don't feel comfortable with anyone sharing their private information.

Is it possible for you to downgrade your Mac, or is this your daily driver?

I'm also more than happy if someone wants to reverse-engineer the new change or create a PR before that.

**Comment by bvlaicu** [comment]
@muehlt I'd rather not downgrade my macOS. That other way of capturing data via iCloud sounds interesting. Do you have any details?

**Comment by kolsha** [comment]
Hi
Any updates on this?

**Comment by ebarellar** [comment]
Check this repo, this is a way to get the key for the encrypted files
https://github.com/MartinPham/FindMySync/blob/2b0824a08adebcac9d17cb54fec13caec16e53d1/FindMySync/Synchronizer.swift#L98

**Comment by kolsha** [comment]
Thanks for the hint.
Although it works, it uses different set of files.
I've been trying to decrypt `Items.data` for the last few days, because it has more information, like battery percentage, but no luck yet.

I'll share my results, maybe someone can bring it further.

It seems that `FMIPDataManagerKey` from keychain is used to encrypt/decrypt this data.
If you delete this key and open `Find my`, the key is created again.

This key/password is in `iCloud` keychain, and when I try get it, it asks me for a password for `"Local Items" keychain`, which I don't know. 
I tried different passwords, none of them worked.

But for some other items, which also asks for `"Local Items" keychain`, it works sometimes, which looks weird.

Anyways, it would be great if someone knows how to solved this puzzle.

**Comment by wilkyconsultants** [comment]
> Thanks for the hint. Although it works, it uses different set of files. I've been trying to decrypt `Items.data` for the last few days, because it has more information, like battery percentage, but no luck yet.
> 
> I'll share my results, maybe someone can bring it further.
> 
> It seems that `FMIPDataManagerKey` from keychain is used to encrypt/decrypt this data. If you delete this key and open `Find my`, the key is created again.
> 
> This key/password is in `iCloud` keychain, and when I try get it, it asks me for a password for `"Local Items" keychain`, which I don't know. I tried different passwords, none of them worked.
> 
> But for some other items, which also asks for `"Local Items" keychain`, it works sometimes, which looks weird.
> 
> Anyways, it would be great if someone knows how to solved this puzzle.

Did you manage to decrypt Items.data yet? I am stuck at Sonoma 14.3 until I can get this worked out for my airtag data harvesting app. thanks!

**Comment by Pnut-GGG** [comment]
I successfully decrypted the findmy data. Check my project for more information.
https://github.com/Pnut-GGG/findmy-cache-decryptor

**Comment by wilkyconsultants** [comment]
> I successfully decrypted the findmy data. Check my project for more information. https://github.com/Pnut-GGG/findmy-cache-decryptor

This is a great breakthrough, congrats! Have you tested this on macOS 15 Sequoia by chance? I am at my cottage so no access to my lab here right now but look forward to trying it when I get back home in a month or so. thanks

**Comment by Pnut-GGG** [comment]
> > I successfully decrypted the findmy data. Check my project for more information. https://github.com/Pnut-GGG/findmy-cache-decryptor
> 
> This is a great breakthrough, congrats! Have you tested this on macOS 15 Sequoia by chance? I am at my cottage so no access to my lab here right now but look forward to trying it when I get back home in a month or so. thanks

I have only tested it on macOS15

Because I only have a Mac with an m4 Pro chip that cannot downgrade the version

That's why I had to research

**Comment by wilkyconsultants** [comment]
> > > I successfully decrypted the findmy data. Check my project for more information. https://github.com/Pnut-GGG/findmy-cache-decryptor
> > 
> > 
> > This is a great breakthrough, congrats! Have you tested this on macOS 15 Sequoia by chance? I am at my cottage so no access to my lab here right now but look forward to trying it when I get back home in a month or so. thanks
> 
> I have only tested it on macOS15
> 
> Because I only have a Mac with an m4 Pro chip that cannot downgrade the version
> 
> That's why I had to research

That's cool, appreciate this effort. 

When I get a chance I will be testing under VM using UTM macos host with a macos 15 guest. Not sure how to set the "csrutil enable" or add boot parms using a VM guest but will check with chatGPT when I am home :) Apple has a nasty habit of changing how all this works almost every version so we will see what they have in store with MacOS Tahoe 26.

**Comment by Pnut-GGG** [comment]
> > > > I successfully decrypted the findmy data. Check my project for more information. https://github.com/Pnut-GGG/findmy-cache-decryptor
> > > 
> > > 
> > > This is a great breakthrough, congrats! Have you tested this on macOS 15 Sequoia by chance? I am at my cottage so no access to my lab here right now but look forward to trying it when I get back home in a month or so. thanks
> > 
> > 
> > I have only tested it on macOS15
> > Because I only have a Mac with an m4 Pro chip that cannot downgrade the version
> > That's why I had to research
> 
> That's cool, appreciate this effort.
> 
> When I get a chance I will be testing under VM using UTM macos host with a macos 15 guest. Not sure how to set the "csrutil enable" or add boot parms using a VM guest but will check with chatGPT when I am home :) Apple has a nasty habit of changing how all this works almost every version so we will see what they have in store with MacOS Tahoe 26.

I have also taken some detours.
I bought a Mac Mini m4 as a home server.
I want to get the location information of FindMy.
I have tried to deploy macOS13 using an UTM virtual machine.
(Unable to use VMware Fusion due to ARM architecture issues)
After the deployment was successful, I disabled SIP but I couldn't log in with my appleid.
Because I used an ipsw image for the deployment.
I also thought about deploying macOS using Docker.
(Unable to successfully deploy because the macOS system does not support KVM)
In the end, I chose to crack the encryption algorithm to achieve the location information of FindMy.
